language: python
python:
  - '2.7'
env:
  global:
    # Contains a GH_TOKEN for the @gds-pp-ci user with public_repo access
    secure: l6AdZ1Zc4Mjsc6qYaYVyxKMtOvs8o6nwuC/0+11Jc4yDYsp2I+NpQRj2roKyXvujbdVjzTd3PGgMUvDcYVxJ4idIZiUROdsrgUt/bv4LHXgABsmAx0K0B5UAQ7sBjGi4X0cTxrx/kF04BCXFY7gDDDzWKTxbZS3oE1XfMPJNKSU=
install:
  - pip install -r requirements_for_tests.txt --use-mirrors
script:
  - ./run_tests.sh
after_success:
  - ./.travis/release_tag.sh
branches:
  except:
    - release
    - /^release_\d+$/
    - /^deployed-to.*$/
notifications:
  email: false
