language: python
python:
  - '2.7'
env:
  global:
    # Contains a GH_TOKEN for the @gds-pp-ci user with public_repo access
    secure: VwHwNKidb1KpFwRmWV2iyh9UIgLO8iOZjC5HZ3QKaiotWBx0IUOk9gsZgvsXYyNdshwHG3zwJaoA0KeBCxVqUyPpTvOU+NSdh7NYdEUt6vgn4HrTbASNvyCnQfNgOoLp9sqXhJeOynHlO9N8mEhmHPHDh9/+O81I5aZ/BJj2smg=
install:
  - pip install -r requirements_for_tests.txt --use-mirrors
script:
  - ./run_tests.sh
after_success:
  - ./.travis/release_tag.sh
branches:
  except:
    - release
    - /^release_\d+$/
    - /^deployed-to.*$/
notifications:
  email: false
